name: Build Kernel

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "u5a_plus_4g_odm_debug_defconfig"
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up Python 3
      uses: actions/setup-python@v3
      with:
        python-version: 3.x

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC-8 date +%m%d%H%M)" >> $GITHUB_ENV

    - name: Fix Python Script Compatibility
      run: |
        # Example: Update the Python script for Python 3 compatibility
        sed -i 's/print \([^)]*\)/print(\1)/g' ../scripts/drvgen/drvgen.py

    - name: Build Kernel
      run: |
        if [[ ! -d gcc ]]; then
          git clone https://github.com/ruben1863/android_gcc_6.4.1_arm-eabi gcc
        fi
        mkdir -p out
        cd kernel-4.4  # Navigate to the kernel directory
        export CROSS_COMPILE=${PWD}/../../gcc/bin/arm-eabi-  # Adjust the path as needed
        export USE_CCACHE=1
        export ARCH=arm
        export SUBARCH=arm
        export TARGET=out
        make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE u5a_plus_4g_odm_debug_defconfig | tee -a Defconfig.log
        make O=$TARGET ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE -j8 | tee -a Kernel.log

    - name: Upload zImage-dtb
      run: |
        curl -T out/arch/arm/boot/zImage-dtb https://bashupload.com/ --output upload_link || { echo "Upload failed"; exit 1; }
        UPLOAD_LINK=$(< upload_link)
        echo "Uploaded file link: $UPLOAD_LINK"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
